version: 1.3.0
title: Shih-Ling Shen
email:  shihling@shihling.com
description: > # this means to ignore newlines until "baseurl:"
  Shih-Ling's Personal Website.
url: "https://shihling.com"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: shihlings
linkedin_username: shih-ling-shen

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - template.md
plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      sitemap: true
  - scope: # stuff under _posts folder
      path: "portfolio/_posts"
    values:
      layout: post
      permalink: /:categories/:year/:title:output_ext